import { LetterDetailType, LetterType } from "@/types/letter";

export const LETTER_DATA: LetterType[] = [
  {
    id: 0,
    url: "aa",
    templateType: 3,
    sender: "승효",
    receiver: "유진주",
    date: "2024-09-04",
    content:
      "전체 스크립트와 관련 있는 렉시컬 환경은 글로벌 렉시컬 환경이다. (Global Lexical Environment)이다. 전역 코드가 시작되면, 렉시컬 환경 객체가 만들어지고, 앞서 선언된 변수와 함수를 해당 레코드에 저장한다.전체 스크립트와 관련 있는 렉시컬 환경은 글로벌 렉시컬 환경이다. (Global Lexical Environment)이다. 전역 코드가 시작되면, 렉시컬 환경 객체가 만들어지고, 앞서 선언된 변수와 함수를 해당 레코드에 저장한다.전체 스크립트와 관련 있는 렉시컬 환경은 글로벌 렉시컬 환경이다. (Global Lexical Environment)이다. 전역 코드가 시작되면, 렉시컬 환경 객체가 만들어지고, 앞서 선언된 변수와 함수를 해당 레코드에 저장한다.",
    images: [],
  },
  {
    id: 1,
    url: "qq",
    templateType: 2,
    sender: "유진주",
    receiver: "승효",
    date: "2024-09-01",
    content: "",
    images: [],
  },
  {
    id: 3,
    url: "circle",
    templateType: 4,
    sender: "김동우",
    receiver: "오민지",
    date: "2024-08-24",
    content:
      "민지 누나 언제나 기획 열정적으로 열심히 해줘서 너무 고마워! 특히 언제나 성실한누나의 모습을 본 받고 싶어. 누나는 꼭멋진 서비스 기획자가 될 거야. 응원할게! ",
    images: [],
  },
  {
    id: 4,
    url: "tocircle",
    templateType: 6,
    sender: "유진주",
    receiver: "김동우",
    date: "2024-08-21",
    content: "",
    images: [],
  },
];

export const LETTER_DETAIL_DATA: LetterDetailType[] = [
  {
    id: 1,
    url: "https://example.com/letter1",
    templateType: 1,
    sender: "철수",
    receiver: "영희",
    content: "안녕, 영희야! 잘 지내고 있지?",
    images: [
      "https://via.assets.so/album.png?id=6&q=95&w=360&h=360&fit=fill",
      "https://via.assets.so/album.png?id=2&q=95&w=360&h=360&fit=fill",
      "https://via.assets.so/album.png?id=3&q=95&w=360&h=360&fit=fill",
    ],
    date: "2024-09-01",
    space_name: "학교 친구들✨",
    letter_count: 1,
    next_letter: {
      letter_id: "2",
      sender_name: "영희",
    },
  },
  {
    id: 2,
    url: "https://example.com/letter/1",
    templateType: 1,
    sender: "백승효",
    receiver: "유진주",
    content: "안녕 진주야~ 레터링 잘 끝내보자!! 화이팅!!",
    images: [
      "https://via.assets.so/album.png?id=6&q=95&w=360&h=360&fit=fill",
      "https://via.assets.so/album.png?id=2&q=95&w=360&h=360&fit=fill",
      "https://via.assets.so/album.png?id=3&q=95&w=360&h=360&fit=fill",
    ],
    date: "2024-09-01",
    space_name: "이것 저것",
    letter_count: 1,
    prev_letter: {
      letter_id: "1",
      sender_name: "유진주",
    },
    next_letter: {
      letter_id: "3",
      sender_name: "김동우",
    },
  },
  {
    id: 3,
    url: "https://example.com/letter/2",
    templateType: 2,
    sender: "백승효",
    receiver: "유진주",
    content: "안녕 진주야~ 레터링 잘 끝내보자!! 화이팅!!",
    images: [
      "https://via.assets.so/album.png?id=6&q=95&w=360&h=360&fit=fill",
      "https://via.assets.so/album.png?id=2&q=95&w=360&h=360&fit=fill",
      "https://via.assets.so/album.png?id=3&q=95&w=360&h=360&fit=fill",
    ],
    date: "2024-09-02",
    space_name: "이것 저것",
    letter_count: 2,
    prev_letter: {
      letter_id: "2",
      sender_name: "홍길동",
    },
    next_letter: {
      letter_id: "4",
      sender_name: "최영준",
    },
  },
  {
    id: 4,
    url: "https://example.com/letter4",
    templateType: 1,
    sender: "지은",
    receiver: "민수",
    content: "민수야, 잘 지내고 있는지 궁금해!",
    images: [],
    date: "2024-09-04",
    space_name: "이것 저것",
    letter_count: 4,
    prev_letter: {
      letter_id: "3",
      sender_name: "민수",
    },
    next_letter: {
      letter_id: "5",
      sender_name: "수현",
    },
  },
  {
    id: 5,
    url: "https://example.com/letter5",
    templateType: 2,
    sender: "수현",
    receiver: "지은",
    content: "지은아, 오랜만이야!",
    images: [],
    date: "2024-09-05",
    space_name: "이것 저것",
    letter_count: 5,
    prev_letter: {
      letter_id: "4",
      sender_name: "지은",
    },
    next_letter: {
      letter_id: "6",
      sender_name: "준호",
    },
  },
  {
    id: 6,
    url: "https://example.com/letter6",
    templateType: 3,
    sender: "준호",
    receiver: "수현",
    content: "수현아, 오랜만이야. 어떻게 지내?",
    images: [],
    date: "2024-09-06",
    space_name: "이것 저것",
    letter_count: 6,
    prev_letter: {
      letter_id: "5",
      sender_name: "수현",
    },
    next_letter: {
      letter_id: "7",
      sender_name: "유나",
    },
  },
  {
    id: 7,
    url: "https://example.com/letter7",
    templateType: 1,
    sender: "유나",
    receiver: "준호",
    content: "준호야, 잘 지내고 있니?",
    images: [],
    date: "2024-09-07",
    space_name: "이것 저것",
    letter_count: 7,
    prev_letter: {
      letter_id: "6",
      sender_name: "준호",
    },
    next_letter: {
      letter_id: "8",
      sender_name: "석진",
    },
  },
  {
    id: 8,
    url: "https://example.com/letter8",
    templateType: 2,
    sender: "석진",
    receiver: "유나",
    content: "유나야, 오랜만에 연락해!",
    images: [],
    date: "2024-09-08",
    space_name: "이것 저것",
    letter_count: 8,
    prev_letter: {
      letter_id: "7",
      sender_name: "유나",
    },
    next_letter: {
      letter_id: "9",
      sender_name: "서현",
    },
  },
  {
    id: 9,
    url: "https://example.com/letter9",
    templateType: 3,
    sender: "서현",
    receiver: "석진",
    content: "석진아, 잘 지내고 있지?",
    images: [],
    date: "2024-09-09",
    space_name: "이것 저것",
    letter_count: 9,
    prev_letter: {
      letter_id: "8",
      sender_name: "석진",
    },
    next_letter: {
      letter_id: "10",
      sender_name: "하늘",
    },
  },
  {
    id: 10,
    url: "https://example.com/letter10",
    templateType: 1,
    sender: "하늘",
    receiver: "서현",
    content: "서현아, 마지막 편지를 보내.",
    images: [],
    date: "2024-09-10",
    space_name: "이것 저것",
    letter_count: 10,
    prev_letter: {
      letter_id: "9",
      sender_name: "서현",
    },
  },
];
